/* GENERATED CODE */
import { PLATFORM } from 'aurelia-pal';

export default [
   { route: '/components/basic/button', name: 'Button', moduleId: PLATFORM.moduleName('./components/basic/button/index'), nav: true },
   { route: '/components/basic/checkbox', name: 'Checkbox', moduleId: PLATFORM.moduleName('./components/basic/checkbox/index'), nav: true },
   { route: '/components/basic/choice-group', name: 'ChoiceGroup', moduleId: PLATFORM.moduleName('./components/basic/choice-group/index'), nav: true },
   { route: '/components/basic/combo-box', name: 'ComboBox', moduleId: PLATFORM.moduleName('./components/basic/combo-box/index'), nav: true },
   { route: '/components/basic/dropdown', name: 'Dropdown', moduleId: PLATFORM.moduleName('./components/basic/dropdown/index'), nav: true },
   { route: '/components/basic/label', name: 'Label', moduleId: PLATFORM.moduleName('./components/basic/label/index'), nav: true },
   { route: '/components/basic/link', name: 'Link', moduleId: PLATFORM.moduleName('./components/basic/link/index'), nav: true },
   { route: '/components/basic/rating', name: 'Rating', moduleId: PLATFORM.moduleName('./components/basic/rating/index'), nav: true },
   { route: '/components/basic/search-box', name: 'SearchBox', moduleId: PLATFORM.moduleName('./components/basic/search-box/index'), nav: true },
   { route: '/components/basic/slider', name: 'Slider', moduleId: PLATFORM.moduleName('./components/basic/slider/index'), nav: true },
   { route: '/components/basic/spin-button', name: 'SpinButton', moduleId: PLATFORM.moduleName('./components/basic/spin-button/index'), nav: true },
   { route: '/components/basic/text-field', name: 'TextField', moduleId: PLATFORM.moduleName('./components/basic/text-field/index'), nav: true },
   { route: '/components/basic/toggle', name: 'Toggle', moduleId: PLATFORM.moduleName('./components/basic/toggle/index'), nav: true },
   { route: '/components/pickers/pickers', name: 'Pickers', moduleId: PLATFORM.moduleName('./components/pickers/pickers/index'), nav: true },
   { route: '/components/items/card', name: 'Card', moduleId: PLATFORM.moduleName('./components/items/card/index'), nav: true },
   { route: '/components/items/persona', name: 'Persona', moduleId: PLATFORM.moduleName('./components/items/persona/index'), nav: true },
   { route: '/components/commands/app-bar', name: 'AppBar', moduleId: PLATFORM.moduleName('./components/commands/app-bar/index'), nav: true },
   { route: '/components/commands/breadcrumb', name: 'Breadcrumb', moduleId: PLATFORM.moduleName('./components/commands/breadcrumb/index'), nav: true },
   { route: '/components/commands/command-bar', name: 'CommandBar', moduleId: PLATFORM.moduleName('./components/commands/command-bar/index'), nav: true },
   { route: '/components/commands/pivot', name: 'Pivot', moduleId: PLATFORM.moduleName('./components/commands/pivot/index'), nav: true },
   { route: '/components/progress/spinner', name: 'Spinner', moduleId: PLATFORM.moduleName('./components/progress/spinner/index'), nav: true },
   { route: '/components/surfaces/dialog', name: 'Dialog', moduleId: PLATFORM.moduleName('./components/surfaces/dialog/index'), nav: true },
   { route: '/components/surfaces/modal', name: 'Modal', moduleId: PLATFORM.moduleName('./components/surfaces/modal/index'), nav: true },
   { route: '/components/surfaces/panel', name: 'Panel', moduleId: PLATFORM.moduleName('./components/surfaces/panel/index'), nav: true },
   { route: '/components/utilities/icon', name: 'Icon', moduleId: PLATFORM.moduleName('./components/utilities/icon/index'), nav: true },
   { route: '/components/utilities/stack', name: 'Stack', moduleId: PLATFORM.moduleName('./components/utilities/stack/index'), nav: true },
];
